version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'forum'
    ports:
      - '5435:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: